steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/xbot-images/xbot-backend:$SHORT_SHA'
      - '.'

  # Step 2: Publish the image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/xbot-images/xbot-backend:$SHORT_SHA'

  # Step 3: Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'xbot-backend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/xbot-images/xbot-backend:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-secrets=spring.datasource.url=DB_URL:latest,spring.datasource.username=DB_USERNAME:latest,spring.datasource.password=DB_PASSWORD:latest,jwt.secret=JWT_SECRET:latest,google.cloud.api.key=GCLOUD_API_KEY:latest,xbot.credentials.bot.api-key=XBOT_API_KEY:latest,xbot.credentials.bot.api-secret=XBOT_API_SECRET:latest,xbot.credentials.bot.access-token=XBOT_ACCESS_TOKEN:latest,xbot.credentials.bot.access-token-secret=XBOT_ACCESS_TOKEN_SECRET:latest,xbot.credentials.bot.jwt-token=XBOT_JWT_TOKEN:latest,xbot.credentials.bot.user-id=XBOT_USER_ID:latest,xbot.credentials.bot.username=XBOT_USERNAME:latest,xbot.blockchain.contract-id=XBOT_CONTRACT_ID:latest,NEAR_PRIVATE_KEY=near-private-key:latest'
      - '--set-env-vars=NEAR_ACCOUNT_ID=xbot-logger.testnet'

  # Step 4: Installing Frontend Dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]
    dir: 'frontend'

  # Step 5: Building the production version of the frontend
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build' ]
    dir: 'frontend'

  # Step 6: Deploy to Firebase Hosting
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --token "$$FIREBASE_TOKEN" --non-interactive --project $PROJECT_ID
    secretEnv: [ 'FIREBASE_TOKEN' ]

# Section to access Firebase token secret
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-deploy-token/versions/latest
      env: 'FIREBASE_TOKEN'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
